### ISSUE TITLE
URGENT Pin colors to 1.4.0 because broken!

### ISSUE THREAD

**Issue by Apollon77** [iobroker-community-adapters/ioBroker.accuweather#146]
https://github.com/iobroker-community-adapters/ioBroker.accuweather/blob/23b22a21acb78843e9eb8761d00018519134866a/package.json#L39

@algar42 Can ypu please pin "colors" to 1.4.0 or remove if not needed?

The package is broken since yesterday in all versions higher then 1.4.0

**Comment by algar42** [comment]
done
