### ISSUE TITLE
Error: Forecast cannot be retrieved. ERROR: [object Object]

### ISSUE THREAD

**Issue by lessthanmore1** [iobroker-community-adapters/ioBroker.accuweather#315]
Hi,

I get the error message "Error: Forecast cannot be retrieved. ERROR: [object Object]" every 5 minutes.

Version 1.3.1.
Everything else's is up to date.

Thank you

**Comment by mcm1957** [comment]
Please add complete version info:
adapter
js-controller
node
O/S

Please add a complete debug log

**Comment by lessthanmore1** [comment]
Adapter version of 
- accuweather: 1.3.1
- js-controller: 5.0.12
- Node.js: 18.18.1
- O/S: Debian, bookworm (Proxmox LXC)

Debug log with the next scheduled run of accuweather/ next post.

**Comment by lessthanmore1** [comment]
There are not additional entries in the log:

`
accuweather.0 | 2023-10-16 10:04:10.434 | error | Error: Forecast cannot be retrieved. ERROR: [object Object]
-- | -- | -- | --
accuweather.0 | 2023-10-16 12:04:11.623 | debug | Date Mon Oct 16 2023 11:57:00 GMT+0200 (Central European Summer Time), dow: Mo
-- | -- | -- | --
accuweather.0 | 2023-10-16 11:04:07.213 | debug | Date Mon Oct 16 2023 10:57:00 GMT+0200 (Central European Summer Time), dow: Mo`

**Comment by Hris2023** [comment]
I unfortunately have the same problem. Here is the output from accuweather:

HTTP/1.1 503 Unauthorized
Connection:
keep-alive
Content-Length:
179
Content-Type:
application/json
Date:
Mon, 23 Oct 2023 16:11:26 GMT
{
  "Code": "ServiceUnavailable",
  "Message": "The allowed number of requests has been exceeded.",
  "Reference": "/currentconditions/v1/locationKey?apikey=XXXXXXXXXXXXXX"
}

**Comment by Hris2023** [comment]
No way to get it working again?

**Comment by peer69** [comment]
Is this a permanent issue for you? As the adapter hits the request limit this error should only occur for some time of the day. Mine goes back to normal every day as soon as the daily api request limit is reset. Back to the error, when the limit is hit again. 
This should probably be solved by either limiting the requests by the adapter or make this limit customizable (see https://github.com/iobroker-community-adapters/ioBroker.accuweather/issues/273) as the daily requests can vary depending on how often you restart your adapter or you might even be using two seperate adapters with the same api key.

**Comment by lessthanmore1** [comment]
> I unfortunately have the same problem.

That is not the same problem. I do not have any issues with the number of requests.
The test under https://developer.accuweather.com/accuweather-current-conditions-api/apis/get/currentconditions/v1/%7BlocationKey%7D works fine for me.
I only struggle with the error message:
`Error: Forecast cannot be retrieved. ERROR: [object Object]`

**Comment by peer69** [comment]
Could you post your output from https://developer.accuweather.com/accuweather-current-conditions-api/apis/get/currentconditions/v1/%7BlocationKey%7D ? 
I get the same error message in ioBroker when the request limit is hit.

**Comment by lessthanmore1** [comment]
`HTTP/1.1 200 OK`
Concerning rate limit:
`RateLimit-Limit:
50
RateLimit-Remaining:
44`

Everything else seems fine. I get the error message occasionally during the day. I'll check if it is related to the rate limit.

**Comment by mcm1957** [comment]
How did you get this output ?

```
HTTP/1.1 200 OK
Concerning rate limit:
RateLimit-Limit: 50 RateLimit-Remaining: 44
```
Could be interesting for logging

**Comment by lessthanmore1** [comment]
> How did you get this output ?
> 
> ```
> HTTP/1.1 200 OK
> Concerning rate limit:
> RateLimit-Limit: 50 RateLimit-Remaining: 44
> ```
> 
> Could be interesting for logging

With the API test. Enter a location, API key and send the request.

**Comment by mcm1957** [comment]
Ok, I see - looks like the info is returned as special headers. Will check if this is only available at website or returned with every request.

Anyway - I have improvements on my todo list, but I do not know when time allows working on it. Sorry.

**Comment by okeck1982** [comment]
Hey everyone,
maybe i found an easy Solution for that Problem. 

When you register an new Application for an AccuWeather account than you can select for different Products. At first it may look like you can select if you want "Core Weather Limited Trial" and/or "MinuteCast Limited Trial". If you click at "MinuteCast Limited Trial" to select one of the MinuteCast options, "Core Weather" is disabled and you get the "Error: Forecast cannot be retrieved. ERROR: [object Object]" Errormessage. 

Resultion:
Go to your AccuWeather Application, click on Edit "<appName>" and select only the "Core Weather Limited Trial" option and save it. 
After that, the error was fixed for me.

Greets
okeck1982
