### ISSUE TITLE
Please add NPM package to iobroker-community-adapters:developers team

### ISSUE THREAD

**Issue by DutchmanNL** [iobroker-community-adapters/ioBroker.accuweather#5]
verifying all repos and NPM ownership we noticed the NPM package of this repo is not part of our team.

please execute : 

`npm access grant read-write iobroker-community-adapters:developers iobroker.<adaptername>`

or add the package by web : 

https://www.npmjs.com/settings/iobroker-community-adapters/teams/team/developers/access

**Comment by algar42** [comment]
@DutchmanNL  Trying to do via console and get the following:
![image](https://user-images.githubusercontent.com/40002726/67081779-7f0b0200-f1a0-11e9-8b96-ffa5450c2afb.png)

The WEB link above says "404 not found" 

what I'm doing wrong??

**Comment by algar42** [comment]
Got user access to iobroker-community-adapters, but still have the same error via console. 
In the web interface I can't find anything that allows me to transfer project.. 

![image](https://user-images.githubusercontent.com/40002726/67120416-ee5d1200-f1f1-11e9-8d9f-19ffd5adce76.png)

**Comment by DutchmanNL** [comment]
i see you were missing rights in NPM, just corrected that.
Please click n packages at the developer team here you can add the package

<img width="1381" alt="Schermafbeelding 2019-10-19 om 13 28 38" src="https://user-images.githubusercontent.com/7318445/67144193-5e13e100-f274-11e9-84a6-9ad89592da4e.png">

**Comment by algar42** [comment]
Should be done now. Could you please check?

**Comment by DutchmanNL** [comment]
> Should be done now. Could you please check?

looks good :)

```
npm access ls-packages iobroker-community-adapters:developers
{
  "iobroker.accuweather": "read-write",
  "iobroker.wlanthermo-nano": "read-write",
  "iobroker.multicast": "read-write",
  "iobroker.knmi-weather": "read-write",
  "iobroker.snmp": "read-write",
  "iobroker.sma-em": "read-write",
  "iobroker.vedirect": "read-write",
  "iobroker.tado": "read-write",
  "iobroker.discovergy": "read-write",
  "iobroker.heytech": "read-write",
  "iobroker.places": "read-write",
  "iobroker.info": "read-write",
  "iobroker.opi": "read-write",
  "iobroker.proxmox": "read-write",
  "iobroker.sony-bravia": "read-write",
  "iobroker.panasonic-viera": "read-write",
  "iobroker.landroid": "read-write",
  "iobroker.fronius": "read-write",
  "iobroker.sourceanalytix": "read-write",
  "iobroker.opentherm": "read-write",
  "iobroker.deconz": "read-write",
  "iobroker.enocean": "read-write",
  "iobroker.upnp": "read-write",
  "iobroker.hmip": "read-write",
  "iobroker.oilfox": "read-write"
}
```
